import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import 'mapbox-gl/dist/mapbox-gl.css';
import { ThemeProvider, Container } from "@mui/material";
import { theme } from "./utils/theme";
import MainNav from "@/app/components/MainNav";
import MobileNavbar from "@/app/components/MobileNavbar";
import Navbar from "@/app/components/Navbar";
import BigFooter from "./components/footer/BigFooter";
import SidebarModel from "@/app/components/model/SidebarModel";
import ProductModel from "./components/model/productModel";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BeBabyShop2 - Betheme",
  description: "Generated by reem",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <SidebarModel />
          <ProductModel/>
          <Navbar />
          <MainNav />
          <MobileNavbar />

          {children}
        </ThemeProvider>
        <Container>
          <BigFooter />
        </Container>
      </body>
    </html>
  );
}
